### ISSUE TITLE
process::Status: pid 343 exit 128

### ISSUE THREAD

**Issue by Krizfrost** [angusmcleod/discourse-topic-previews#104]
Whenever I tried to add this plugin to my discourse, on building of launcher, I kept getting this error display for some reason, Unsure what it pertains to or what is causing the issue.

**Comment by merefield** [comment]
Issues are no longer maintained here as per the README.

I do not recognise your issue as one reported by any other users of the plugin.

Have you searched meta?  I found https://meta.discourse.org/search?q=process%3A%3AStatus%3A%20pid%20exit
