### ISSUE TITLE
Layout settings refactoring

### ISSUE THREAD

**Issue by pmusaraj** [angusmcleod/discourse-topic-previews#13]
Below is a plan on how we can simplify and clarify the settings, while covering more use cases than currently supported (i.e. targeting specific lists). 

Replace the following settings: 
- topic list thumbnails (boolean)
- topic list excerpts (boolean)
- topic list social media discovery (boolean)
- topic list social media only latest (boolean)
- topic list social media only latest disable thumbnails (boolean)

with: 

topic list display social media layout (option list)
options: nowhere, on all lists, "on latest, new and unread", on latest and new, on latest only

topic list display thumbnails (option list)
options: nowhere, on all lists, only where social media layout is active

topic list excerpts (option list)
options: nowhere, on all lists, only where social media layout is active

topic list actions (option list)
options: nowhere, on all lists, only where social media layout is active

_Notes_
How does this affect the mobile layout? Should we keep the `topic list mobile previews` checkbox and if checked, all the settings above apply to mobile as well? Or should we have more flexibility? 

The 4 new settings fields above should be replicated on the category settings screen, that way the same options can apply to that category.

**Comment by angusmcleod** [comment]
I agree the settings need to change, but I would take a slightly different approach.

In particular using the list setting format, e.g.

![screen shot 2016-10-14 at 4 37 49 pm](https://cloud.githubusercontent.com/assets/5931623/19402011/97eaaa7c-922c-11e6-8f2c-12a8cfd861b4.png)

This allows all combinations, or all or none, without spelling out each permutation. I think this allows us to integrate the mobile view approach at the same time.

- 'topic list social media layout' (no need to include 'display'): latest | new | unread | latest mobile | new mobile | unread mobile 
- 'topic list thumbnails' (no need to include 'display'): latest | new | unread | latest mobile | new mobile | unread mobile 
- 'topic list excerpts': latest | new | unread | latest mobile | new mobile | unread mobile 
- 'topic list actions': latest | new | unread | latest mobile | new mobile | unread mobile

> The 4 new settings fields above should be replicated on the category settings screen, that way the same options can apply to that category.

👍

**Comment by pmusaraj** [comment]
Ah, yeah, this is better and solves the mobile issue. 

I will start working on this at some point this week.

**Comment by angusmcleod** [comment]
@pmusaraj Fantastic. Thanks!
