### ISSUE TITLE
Thumbnails not generating for previews after upgrade

### ISSUE THREAD

**Issue by corbettbarr** [angusmcleod/discourse-topic-previews#17]
Hello Angus, thanks for the fantastic topic previews plugin for Discourse.

I recently upgraded Discourse to v1.7.0.beta6 +83. Since then, new posts aren't generating image thumbnails for the previews. 

My discourse-topic-previews shows that it is up to date (96964f1).

Is there something else I'm supposed to run after an upgrade?

**Comment by angusmcleod** [comment]
@corbettbarr Hey, yes there was a change to Discourse core that affected this plugin. I just committed a fix.

https://github.com/angusmcleod/discourse-topic-previews/commit/c260a16834d14c91c0b22cd59ce969afe186aa9f

**Comment by corbettbarr** [comment]
Thanks so much!
