### ISSUE TITLE
Prep plugin for upcoming Ember 2.4 release

### ISSUE THREAD

**Issue by pmusaraj** [angusmcleod/discourse-topic-previews#19]
Discourse core is updating to Ember 2.4, and the plugin doesn't yet work with it. 

See this: https://meta.discourse.org/t/upgrading-ember-to-2-4/52724 

Issues so far

- [x] Ember no longer allows setting values during didInsertElement
- [x] Thumbnails missing
- [x] Actions missing
- [x] Topic intro missing in social layout

I created a `ember-2.4` branch for the plugin, @angusmcleod and testing it with Discourse's `ember-2.4` branch.

**Comment by angusmcleod** [comment]
@pmusaraj Thanks for raising this. I will take a closer look tomorrow using your list.

ps. @eviltrout helped us out with 1 as well: https://github.com/angusmcleod/discourse-topic-previews/pull/20

**Comment by angusmcleod** [comment]
@pmusaraj I've moved the desktop topic list to a dedicated template. It just got too complex with the previous approach. I think it's ready to go. Could you give it a look over?

https://github.com/angusmcleod/discourse-topic-previews/commit/d367de79652c1a0a4405d572c4508c5a36165f16

**Comment by pmusaraj** [comment]
Yep, this looks good on desktop. I did find several issues on mobile, and it looks like it was all due to the name of the template file for mobile. I renamed it in latest commit on the `ember-2.4` branch and it seems to be in good shape now.

**Comment by angusmcleod** [comment]
Merged.
