### ISSUE TITLE
Job exception: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by alonle** [angusmcleod/discourse-topic-previews#26]
Hi, 
I have the latest test-passed discourse (v1.9.0.beta8 +102)

I have an error with the plugin:
Job exception: undefined method `[]' for nil:NilClass

This is the stack trace:
/var/www/discourse/plugins/discourse-topic-previews/plugin.rb:164:in `update_post_image'
/var/www/discourse/lib/cooked_post_processor.rb:311:in `post_process_oneboxes'
/var/www/discourse/lib/cooked_post_processor.rb:34:in `block in post_process'
/var/www/discourse/lib/distributed_mutex.rb:21:in `synchronize'
/var/www/discourse/lib/distributed_mutex.rb:5:in `synchronize'
/var/www/discourse/lib/cooked_post_processor.rb:31:in `post_process'
/var/www/discourse/app/jobs/regular/process_post.rb:24:in `execute'
/var/www/discourse/app/jobs/base.rb:153:in `block (2 levels) in perform'

Do we need to check if img is null?
Thanks

**Comment by angusmcleod** [comment]
Resolved by https://github.com/angusmcleod/discourse-topic-previews/commit/8889e6b24a66970a6a5a54a646b1868aef7561c7
