### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined - BUG?

### ISSUE THREAD

**Issue by dalerka** [angusmcleod/discourse-topic-previews#27]
Hi, thank you for this amazing plugin. I'm using it on two discourse installations and on one of them it works well, but on another (fresh install no traffic yet) I keep getting this error:
`TypeError: Cannot read property 'split' of undefined` after installing it and rebuilding the `app containter`. Both installations are simple one-container and on separate VPSes. 

So, I get this error in the browser console when I go to a specific _Category_ page and click the _"Edit"_ button. The _Category Edit_ dialog appears but I cannot go to other tabs, but _"General"_.

The problem disappears when I remove this plugin and rebuild the app, but comes back again when this plugin is added. Currently I don't have other 3rd party plugins.

Can someone share hints?

**Comment by angusmcleod** [comment]
Fixed in: https://github.com/angusmcleod/discourse-topic-previews/commit/a6fc2c2b5bb986ae03eaad68a1c0ec905172ee38
