### ISSUE TITLE
TypeError: Cannot read property 'topic_list_social' of undefined

### ISSUE THREAD

**Issue by dalerka** [angusmcleod/discourse-topic-previews#28]
Hi, when I go to "Categories" page (on a fresh Discourse forum instance with only this 3rd party plugin enabled) and click "Create new category" the following error appears in the browser console and I cannot create a new category:
`TypeError: Cannot read property 'topic_list_social' of undefined`

The "New Category" dialog becomes dysfunctional (tabs, form elements and buttons not working) and only shows "General" tab. 

However the "Edit category" dialog works as expected. 
I have the _"topic list social"_ enabled for `latest, top, latest-mobile, top-mobile`.

**Comment by angusmcleod** [comment]
Thanks, fixed: https://github.com/angusmcleod/discourse-topic-previews/commit/53e540080636e73445b8c498c932aa6a8ae14923
