### ISSUE TITLE
Descriptive README

### ISSUE THREAD

**Issue by caugner** [angusmcleod/discourse-topic-previews#4]
Could you provide a more descriptive [README](https://github.com/angusmcleod/discourse-topic-previews/blob/master/README.md) which explains what the plugin does?

See [babble’s README](https://github.com/gdpelican/babble/blob/master/README.md) for a good example which includes:
- [ ] Link to Demo site (if exists)
- [ ] Install instructions
- [ ] Usage instructions
- [ ] List of current features
- [ ] List of future features
- [ ] Translation instructions (once applicable)

**Comment by angusmcleod** [comment]
Hey. I will soonish :)

In the meantime, the linked Discourse topic serves as a readme.

**Comment by angusmcleod** [comment]
Hey I have recently updated the first post in the TLP topic with a more descriptive guide to the plugin's features:

https://meta.discourse.org/t/topic-list-previews/41630
