### ISSUE TITLE
Link update needed in README.md

### ISSUE THREAD

**Issue by tanius** [angusmcleod/discourse-topic-previews#56]
Due to a recent change of the Discourse topic with the plugin's documentation, [`README.md`](https://github.com/angusmcleod/discourse-topic-previews/blob/master/README.md) needs an update. The new link is:

https://meta.discourse.org/t/101646

**Comment by merefield** [comment]
Good reminder, thanks for reporting

**Comment by merefield** [comment]
This is fixed now
